stages:
  - build
  - deploy

# Build for all commits and environments
build:
  stage: build
  script:
    - sudo -E /occrp/scripts/id/build-assets.sh
  tags:
    - zam

# Deploy on testing environment
deploy-test:
  stage: deploy
  script:
    - sudo -E /occrp/scripts/id/deploy-assets.sh
  environment:
    name: test-id
    url: https://test.id.occrp.org
  tags:
    - zam

# Deploy on production environment only for master branch
deploy-prod:
  stage: deploy
  script:
    - sudo -E /occrp/scripts/id/deploy-assets.sh
  environment:
    name: id
    url: https://id.occrp.org
  only:
    - master
  tags:
    - zam