# testing environment
master-cdn-deploy:
  stage: deploy
  script:
  - npm install
  - npm install ember-cli
  - npm run lint:js
  - node_modules/ember-cli/bin/ember test --launch=Chromium --filter='!flanky'
  - node_modules/ember-cli/bin/ember build --environment production
  - rsync -av --delete dist/ /output/id-frontend/
  only:
  - master
  tags:
  - master

# production environment
master-tagged-cdn-deploy:
  stage: deploy
  script:
  - npm install
  - npm install ember-cli
  - npm run lint:js
  - node_modules/ember-cli/bin/ember test --launch=Chromium --filter='!flanky'
  - node_modules/ember-cli/bin/ember build --environment production
  - rsync -av --delete dist/ /output/id-frontend/
  only:
  - tags
  except:
  - branches
  tags:
  - production
