# testing environment
master-cdn-deploy:
  stage: deploy
  script:
  - docker-compose run --rm ember npm install
  - ./ember build --environment production
  - rsync -av --delete dist/ /output/id-frontend/
  only:
  - master
  tags:
  - master
