# testing environment
master-cdn-deploy:
  stage: deploy
  script:
  - npm install
  - npm install ember-cli
  - npm run lint:js
  - node_modules/ember-cli/bin/ember test --launch=Chromium --filter='!flanky'
  - node_modules/ember-cli/bin/ember build --environment production
  - rsync -av --delete dist/ /output/id-frontend/
  only:
  - master
  tags:
  - master

# production environment
master-tagged-cdn-deploy:
  stage: deploy
  script:
  - npm install
  - npm install ember-cli
  - npm run lint:js
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - apt-get update && apt-get install -yq google-chrome-stable
  - npm run test:ci
  - node_modules/ember-cli/bin/ember test --launch=Chrome --filter='!flanky'
  - node_modules/ember-cli/bin/ember build --environment production
  - rsync -av --delete dist/ /output/id-frontend/
  only:
  - tags
  except:
  - branches
  tags:
  - production
