version: '3'

services:
  ember:
    image: ember-cli
    build: ./
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tmpfs:
      - /app/tmp
    environment:
      - EMBER_SERVE_ARGS=${EMBER_SERVE_ARGS}
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
    command: 'ember serve $EMBER_SERVE_ARGS'

volumes:
  node_modules:
